
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ferec
 */
public class StockApp extends javax.swing.JFrame {

	/**
	 * Creates new form StockApp
	 */
	public StockApp() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		productName = new javax.swing.JTextField();
		cb_category = new javax.swing.JComboBox<>();
		priceField = new javax.swing.JTextField();
		messageNotice = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		productTable = new javax.swing.JTable();
		addProduct = new javax.swing.JButton();
		updateProducts = new javax.swing.JButton();
		deleteProduct = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("StockApp");

		jLabel1.setText("Product Name");

		jLabel2.setText("Category");

		jLabel3.setText("Price ($)");

		cb_category.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Culture and Art", "Food", "Electronics" }));

		messageNotice.setForeground(new java.awt.Color(255, 51, 51));

		productTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Product Name", "Category", "Price ($)" }));
		productTable.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				productTableMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(productTable);

		addProduct.setText("Add Product");
		addProduct.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addProductActionPerformed(evt);
			}
		});

		updateProducts.setText("Update Products");
		updateProducts.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				updateProductsActionPerformed(evt);
			}
		});

		deleteProduct.setText("Delete Product");
		deleteProduct.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				deleteProductActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(102, 102, 255));
		jLabel4.setText(
				"                                                                                      Made by Ferec Hamitbeyli");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(27, 27, 27)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(messageNotice, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel2).addComponent(jLabel3))
										.addGap(34, 34, 34))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addComponent(jLabel1).addGap(18, 18, 18)))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(productName).addComponent(cb_category, 0, 193, Short.MAX_VALUE)
										.addComponent(priceField))
								.addGap(40, 40, 40)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(updateProducts, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(addProduct, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(deleteProduct, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addComponent(jScrollPane1))
				.addContainerGap(24, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel4).addGap(40, 40, 40)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addGap(27, 27, 27)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addContainerGap().addComponent(addProduct)))
				.addGap(11, 11, 11)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
						.addComponent(cb_category, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(updateProducts))
				.addGap(13, 13, 13)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3)
						.addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(deleteProduct))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(messageNotice, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel4)
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void addProductActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addProductActionPerformed
		messageNotice.setText("");
		DefaultTableModel model = (DefaultTableModel) productTable.getModel();

		if (productName.getText().trim().equals("")) {
			messageNotice.setText("Product name can not be blank.");
		} else {
			Object[] willAdd = { productName.getText(), cb_category.getSelectedItem().toString(),
					priceField.getText() };
			model.addRow(willAdd);

		}
	}// GEN-LAST:event_addProductActionPerformed

	private void updateProductsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateProductsActionPerformed
		messageNotice.setText("");
		DefaultTableModel model = (DefaultTableModel) productTable.getModel();
		int selectedRow = productTable.getSelectedRow();
		if (selectedRow == -1) {
			if (productTable.getRowCount() == 0) {
				messageNotice.setText("Product table is currently empty.");
			} else {
				messageNotice.setText("Please select a product to update.");
			}
		} else {
			model.setValueAt(productName.getText(), selectedRow, 0);
			model.setValueAt(cb_category.getSelectedItem().toString(), selectedRow, 1);
			model.setValueAt(priceField.getText(), selectedRow, 2);
			messageNotice.setText("Product has been successfully updated.");
		}
	}// GEN-LAST:event_updateProductsActionPerformed

	private void productTableMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_productTableMouseClicked
		DefaultTableModel model = (DefaultTableModel) productTable.getModel();
		int selectedRow = productTable.getSelectedRow();
		productName.setText(model.getValueAt(selectedRow, 0).toString());
		cb_category.setSelectedItem(model.getValueAt(selectedRow, 1).toString());
		priceField.setText(model.getValueAt(selectedRow, 2).toString());

	}// GEN-LAST:event_productTableMouseClicked

	private void deleteProductActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteProductActionPerformed
		messageNotice.setText("");
		DefaultTableModel model = (DefaultTableModel) productTable.getModel();
		int selectedRow = productTable.getSelectedRow();
		if (selectedRow == -1) {
			if (productTable.getRowCount() == 0) {
				messageNotice.setText("Product table is currently empty.");
			} else {
				messageNotice.setText("Please select a product to delete.");
			}
		} else {
			model.removeRow(selectedRow);
			messageNotice.setText("The product has been successfully deleted.");
		}
	}// GEN-LAST:event_deleteProductActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(StockApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(StockApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(StockApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(StockApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new StockApp().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addProduct;
	private javax.swing.JComboBox<String> cb_category;
	private javax.swing.JButton deleteProduct;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel messageNotice;
	private javax.swing.JTextField priceField;
	private javax.swing.JTextField productName;
	private javax.swing.JTable productTable;
	private javax.swing.JButton updateProducts;
	// End of variables declaration//GEN-END:variables
}
